development:
  path: http://localhost:3000

production:
  path: https://frozen-gorge-39153.herokuapp.com/

staging:
  path: https://battleshift-staging.herokuapp.com/

test:
  path: http://localhost:3000
